### ISSUE TITLE
сконфигурировать докер, чтобы nginx лежал отдельно от фронтенда и сервил api на mospan.pro/api/, а фронтенд на mospan.pro (2000₽)

### ISSUE THREAD

**Issue by alex-mos** [alex-mos/mospan_pro_frontend#2]
Сейчас контейнер mospan_pro_frontend включает в себя образ с фронтенд-приложением на vue и образ nginx, который сконфигурирован на раздачу этого vue-приложения.
Требуется выделить образ с nginx в отдельный контейнер mospan_pro_deploy, который будет сконфигурирован на раздачу бекенда контейнера mospan_pro_backend с адреса mospan.pro/api и контейнера фронтенда mospan_pro_frontend с адреса mospan.pro.
Это нужно для возможности раздачи многих приложений с сервера простым добавлением приложений в конфиг nginx, запущенного в отдельном контейнере.

**Comment by maximal** [comment]
Не совсем понятна конкретная задача, поэтому рассмотрел два варианта:

## 1. Мы хотим балансировать нагрузку

В таком случае нам нужно несколько идентичных контейнеров с фронтендом и несколько идентичных контейнеров с бекендом.
См. контейнеры `frontend1` и `frontend2`.

Не уверен, что правильно решил эту задачу, потому что Докер, вроде как, сам умеет балансировать, и всё такое.
Ну для полноты картины пусть будет и балансировка на стороне Нжинкса.

## 2. Нам просто нужны независимые приложения

Тогда просто делаем сколько надо контейнеров и мапим порты, например 8061:8080 (из внутреннего 8080 во внешний 8061).
См. контейнеры, которые висят на поддоменах:
* `frontend3` — это приложение app3.mospan.pro;
* `frontend4` — это приложение app4.mospan.pro.

PS: Спасибо, что дал возможность поразбираться с Докером.
